/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DB.MongoConnection;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.awt.FlowLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import org.bson.Document;
import View.WrapLayout;
/**
 *
 * @author ADVAN
 */
public class DataKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    public DataKaryawan() {
        initComponents();
        panelRounded1.setLayout(new java.awt.GridLayout(0, 4, 15, 15));
        loadDataKaryawan();
    
        SwingUtilities.invokeLater(() -> {
        // Icon Dashboard (jLabel3)
        ImageIcon icon3 = new ImageIcon(getClass().getResource("/assets/dashboard.png"));
        Image img3 = icon3.getImage();
        double ratio3 = Math.min((double) jLabel3.getWidth() / icon3.getIconWidth(),
                                  (double) jLabel3.getHeight() / icon3.getIconHeight());
        jLabel3.setIcon(new ImageIcon(img3.getScaledInstance(
            (int)(icon3.getIconWidth() * ratio3),
            (int)(icon3.getIconHeight() * ratio3),
            Image.SCALE_SMOOTH)));
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setVerticalAlignment(SwingConstants.CENTER);

        // Icon Data Karyawan (jLabel4)
        ImageIcon icon4 = new ImageIcon(getClass().getResource("/assets/karyawan.png"));
        Image img4 = icon4.getImage();
        double ratio4 = Math.min((double) jLabel4.getWidth() / icon4.getIconWidth(),
                                  (double) jLabel4.getHeight() / icon4.getIconHeight());
        jLabel4.setIcon(new ImageIcon(img4.getScaledInstance(
            (int)(icon4.getIconWidth() * ratio4),
            (int)(icon4.getIconHeight() * ratio4),
            Image.SCALE_SMOOTH)));
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setVerticalAlignment(SwingConstants.CENTER);

        // Icon Laporan (jLabel5)
        ImageIcon icon5 = new ImageIcon(getClass().getResource("/assets/laporan.png"));
        Image img5 = icon5.getImage();
        double ratio5 = Math.min((double) jLabel5.getWidth() / icon5.getIconWidth(),
                                  (double) jLabel5.getHeight() / icon5.getIconHeight());
        jLabel5.setIcon(new ImageIcon(img5.getScaledInstance(
            (int)(icon5.getIconWidth() * ratio5),
            (int)(icon5.getIconHeight() * ratio5),
            Image.SCALE_SMOOTH)));
        jLabel5.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel5.setVerticalAlignment(SwingConstants.CENTER);
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtextfieldRounded1 = new jtextfield.JtextfieldRounded();
        jLabel12 = new javax.swing.JLabel();
        buttonRounded1 = new jtextfield.ButtonRounded();
        buttonRounded2 = new jtextfield.ButtonRounded();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelRounded1 = new jtextfield.PanelRounded();
        buttonRounded3 = new jtextfield.ButtonRounded();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(31, 73, 125));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashboard.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/karyawan.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/laporan.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data Karyawan");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Keluar");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logout.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Laporan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(49, 49, 49))
        );

        jLabel10.setBackground(new java.awt.Color(31, 73, 125));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(31, 73, 125));
        jLabel10.setText("Data Karyawan");

        jtextfieldRounded1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldRounded1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Cari Nama");

        buttonRounded1.setBackground(new java.awt.Color(216, 224, 252));
        buttonRounded1.setForeground(new java.awt.Color(31, 73, 125));
        buttonRounded1.setText("Cari");
        buttonRounded1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonRounded1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounded1ActionPerformed(evt);
            }
        });

        buttonRounded2.setBackground(new java.awt.Color(154, 210, 255));
        buttonRounded2.setForeground(new java.awt.Color(31, 73, 125));
        buttonRounded2.setText("Buat");
        buttonRounded2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonRounded2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounded2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(panelRounded1);

        buttonRounded3.setBackground(new java.awt.Color(153, 255, 153));
        buttonRounded3.setText("Refresh");
        buttonRounded3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonRounded3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounded3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtextfieldRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(buttonRounded2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonRounded3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(188, 188, 188))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextfieldRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRounded2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRounded3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfieldRounded1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldRounded1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldRounded1ActionPerformed

    private void buttonRounded1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounded1ActionPerformed
    String keyword = jtextfieldRounded1.getText().trim();
    if (keyword.isEmpty()) {
        loadDataKaryawan(); // tampilkan semua kalau kosong
    } else {
        cariKaryawan(keyword);
    }
    }//GEN-LAST:event_buttonRounded1ActionPerformed

    private void buttonRounded3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounded3ActionPerformed
    jtextfieldRounded1.setText(""); // kosongkan search field
    loadDataKaryawan(); 
    }//GEN-LAST:event_buttonRounded3ActionPerformed

    private void buttonRounded2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounded2ActionPerformed
    FormKaryawan form = new FormKaryawan(this, true);
    form.setVisible(true);
    if (form.isSaved()) {
        loadDataKaryawan();
    }
    }//GEN-LAST:event_buttonRounded2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jtextfield.ButtonRounded buttonRounded1;
    private jtextfield.ButtonRounded buttonRounded2;
    private jtextfield.ButtonRounded buttonRounded3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private jtextfield.JtextfieldRounded jtextfieldRounded1;
    private jtextfield.PanelRounded panelRounded1;
    // End of variables declaration//GEN-END:variables

private void loadDataKaryawan() {
    panelRounded1.removeAll();
    panelRounded1.setLayout(new WrapLayout(FlowLayout.LEFT, 10, 10));
    
    try {
        MongoDatabase db = MongoConnection.getDatabase();
        MongoCollection<Document> collection = db.getCollection("Karyawan");
        for (Document doc : collection.find()) {
            String nama = doc.getString("nama");
            String nik = doc.getString("nik");
            String jabatan = doc.getString("jabatan");
            String dept = doc.getString("departemen");
            String status = doc.getString("status");
            
            KaryawanCard card = new KaryawanCard(nama, nik, jabatan, dept, status, new KaryawanCard.CardListener() {
                @Override
                public void onEdit(String nikKaryawan) {
                    FormKaryawan form = new FormKaryawan(DataKaryawan.this, true, nikKaryawan);
                    form.setVisible(true);
                    if (form.isSaved()) {
                        loadDataKaryawan();
                    }
                }
                @Override
                public void onDelete(String nikKaryawan) {
                    int confirm = JOptionPane.showConfirmDialog(DataKaryawan.this,
                        "Yakin hapus karyawan ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.YES_OPTION) {
                        collection.deleteOne(new Document("nik", nikKaryawan));
                        loadDataKaryawan();
                    }
                }
            });
            card.setPreferredSize(new java.awt.Dimension(220, 190));
            panelRounded1.add(card);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
    }
    panelRounded1.revalidate();
    panelRounded1.repaint();
}
private void cariKaryawan(String keyword) {
    panelRounded1.removeAll();
    panelRounded1.setLayout(new WrapLayout(FlowLayout.LEFT, 10, 10));
    
    try {
        MongoDatabase db = MongoConnection.getDatabase();
        MongoCollection<Document> collection = db.getCollection("Karyawan");
        
        Document filter = new Document("nama", 
            new Document("$regex", keyword).append("$options", "i"));
        
        for (Document doc : collection.find(filter)) {
            String nama = doc.getString("nama");
            String nik = doc.getString("nik");
            String jabatan = doc.getString("jabatan");
            String dept = doc.getString("departemen");
            String status = doc.getString("status");
            
            // baris 436 (diganti jadi blok panjang):
KaryawanCard card = new KaryawanCard(nama, nik, jabatan, dept, status, new KaryawanCard.CardListener() {
    @Override
    public void onEdit(String nikKaryawan) {
        FormKaryawan form = new FormKaryawan(DataKaryawan.this, true, nikKaryawan);
        form.setVisible(true);
        if (form.isSaved()) {
            cariKaryawan(keyword);
        }
    }
    @Override
    public void onDelete(String nikKaryawan) {
        int confirm = JOptionPane.showConfirmDialog(DataKaryawan.this,
            "Yakin hapus karyawan ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                MongoDatabase db = MongoConnection.getDatabase();
                MongoCollection<Document> col = db.getCollection("Karyawan");
                col.deleteOne(new Document("nik", nikKaryawan));
                cariKaryawan(keyword);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(DataKaryawan.this, "Gagal hapus: " + ex.getMessage());
            }
        }
    }
});
// baris 437-439 tetap:
card.setPreferredSize(new java.awt.Dimension(220, 190));
panelRounded1.add(card);
            card.setPreferredSize(new java.awt.Dimension(220, 190)); // ✅ di dalam loop
            panelRounded1.add(card);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal cari data: " + e.getMessage());
    }
    
    panelRounded1.revalidate();
    panelRounded1.repaint();
}
}
