/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DB.MongoConnection;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.awt.Frame;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author ADVAN
 */
public class FormKaryawan extends javax.swing.JDialog {

private boolean saved = false;
private boolean isEditMode = false; 


public boolean isSaved() {
    return saved;
}

public FormKaryawan(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] { "aktif", "non-aktif" }
    ));
    
    setLocationRelativeTo(parent);
}

public FormKaryawan(java.awt.Frame parent, boolean modal, String nikEdit) {
    super(parent, modal);
    initComponents();
    
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] { "aktif", "non-aktif" }
    ));
    
    setLocationRelativeTo(parent);
    isEditMode = true;
    
    try {
        MongoDatabase db = MongoConnection.getDatabase();
        MongoCollection<Document> collection = db.getCollection("Karyawan");
        Document doc = collection.find(new Document("nik", nikEdit)).first();
        if (doc != null) {
            jtextfieldRounded1.setText(doc.getString("nama"));
            jtextfieldRounded3.setText(doc.getString("nik"));
            jtextfieldRounded4.setText(doc.getString("jabatan"));
            jtextfieldRounded5.setText(doc.getString("departemen"));
            jComboBox1.setSelectedItem(doc.getString("status"));
            jtextfieldRounded3.setEditable(false);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRounded1 = new jtextfield.PanelRounded();
        jtextfieldRounded1 = new jtextfield.JtextfieldRounded();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtextfieldRounded3 = new jtextfield.JtextfieldRounded();
        jLabel3 = new javax.swing.JLabel();
        jtextfieldRounded4 = new jtextfield.JtextfieldRounded();
        jtextfieldRounded5 = new jtextfield.JtextfieldRounded();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        buttonRounded1 = new jtextfield.ButtonRounded();
        buttonRounded2 = new jtextfield.ButtonRounded();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelRounded1.setBackground(new java.awt.Color(47, 105, 176));

        jtextfieldRounded1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldRounded1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tag-RFID");

        jtextfieldRounded3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldRounded3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jabatan");

        jtextfieldRounded4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldRounded4ActionPerformed(evt);
            }
        });

        jtextfieldRounded5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldRounded5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dapartemen");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");

        buttonRounded1.setBackground(new java.awt.Color(204, 255, 204));
        buttonRounded1.setForeground(new java.awt.Color(51, 204, 0));
        buttonRounded1.setText("Simpan");
        buttonRounded1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonRounded1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounded1ActionPerformed(evt);
            }
        });

        buttonRounded2.setBackground(new java.awt.Color(255, 204, 204));
        buttonRounded2.setForeground(new java.awt.Color(255, 0, 51));
        buttonRounded2.setText("Batal");
        buttonRounded2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonRounded2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounded2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRounded1Layout = new javax.swing.GroupLayout(panelRounded1);
        panelRounded1.setLayout(panelRounded1Layout);
        panelRounded1Layout.setHorizontalGroup(
            panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRounded1Layout.createSequentialGroup()
                .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRounded1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(buttonRounded2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRounded1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRounded1Layout.createSequentialGroup()
                                .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtextfieldRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addGroup(panelRounded1Layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtextfieldRounded3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtextfieldRounded4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buttonRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtextfieldRounded5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelRounded1Layout.setVerticalGroup(
            panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRounded1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtextfieldRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtextfieldRounded3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtextfieldRounded4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtextfieldRounded5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(panelRounded1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRounded2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfieldRounded1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldRounded1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldRounded1ActionPerformed

    private void jtextfieldRounded3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldRounded3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldRounded3ActionPerformed

    private void jtextfieldRounded4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldRounded4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldRounded4ActionPerformed

    private void jtextfieldRounded5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldRounded5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldRounded5ActionPerformed

    private void buttonRounded2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounded2ActionPerformed
    dispose();
    }//GEN-LAST:event_buttonRounded2ActionPerformed

    private void buttonRounded1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounded1ActionPerformed
    String nama = jtextfieldRounded1.getText().trim();
    String nik = jtextfieldRounded3.getText().trim();
    String jabatan = jtextfieldRounded4.getText().trim();
    String dept = jtextfieldRounded5.getText().trim();
    String status = jComboBox1.getSelectedItem().toString();

    if (nama.isEmpty() || nik.isEmpty() || jabatan.isEmpty() || dept.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!",
            "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        MongoDatabase db = MongoConnection.getDatabase();
        MongoCollection<Document> collection = db.getCollection("Karyawan");

    Document doc = new Document("nama", nama)
        .append("nik", nik)
        .append("jabatan", jabatan)
        .append("departemen", dept)
        .append("status", status);

    if (isEditMode) {
        collection.replaceOne(new Document("nik", nik), doc);
    } else {
        if (collection.find(new Document("nik", nik)).first() != null) {
            JOptionPane.showMessageDialog(this, "NIK sudah terdaftar!",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        collection.insertOne(doc);
    }
        this.saved = true;
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
    }
    }//GEN-LAST:event_buttonRounded1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new FormKaryawan(null, true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jtextfield.ButtonRounded buttonRounded1;
    private jtextfield.ButtonRounded buttonRounded2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private jtextfield.JtextfieldRounded jtextfieldRounded1;
    private jtextfield.JtextfieldRounded jtextfieldRounded3;
    private jtextfield.JtextfieldRounded jtextfieldRounded4;
    private jtextfield.JtextfieldRounded jtextfieldRounded5;
    private jtextfield.PanelRounded panelRounded1;
    // End of variables declaration//GEN-END:variables
}
