/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author ADVAN
 */
public class LoginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdmin
     */
    public LoginAdmin() {
        initComponents();
        
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
    // Paksa jPanel1 ngikut ukuran layar saat window resize
    this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            jPanel1.setSize(getContentPane().getWidth(), getContentPane().getHeight());
        }
    });
        
   SwingUtilities.invokeLater(() -> {
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/assets/download_edited.png"));
        Image originalImage = originalIcon.getImage();
        
        int labelW = jLabel2.getWidth();
        int labelH = jLabel2.getHeight();
        
        int imgW = originalIcon.getIconWidth();
        int imgH = originalIcon.getIconHeight();
        
        double ratioW = (double) labelW / imgW;
        double ratioH = (double) labelH / imgH;
        double ratio = Math.min(ratioW, ratioH);
        
        int newW = (int) (imgW * ratio);
        int newH = (int) (imgH * ratio);
        
        Image scaledImage = originalImage.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
        jLabel2.setIcon(new ImageIcon(scaledImage));
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setVerticalAlignment(SwingConstants.CENTER);
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRounded1 = new jtextfield.PanelRounded();
        panelRounded2 = new jtextfield.PanelRounded();
        jLabel1 = new javax.swing.JLabel();
        jtextfieldRounded1 = new jtextfield.JtextfieldRounded();
        jtextfieldRounded2 = new jtextfield.JtextfieldRounded();
        buttonRounded1 = new jtextfield.ButtonRounded();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        panelRounded1.setBackground(new java.awt.Color(255, 255, 255));
        panelRounded1.setForeground(new java.awt.Color(204, 255, 255));
        panelRounded1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRounded2.setBackground(new java.awt.Color(241, 241, 241));
        panelRounded2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN ADMIN");
        panelRounded2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 340, 60));

        jtextfieldRounded1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldRounded1ActionPerformed(evt);
            }
        });
        panelRounded2.add(jtextfieldRounded1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 260, 50));

        jtextfieldRounded2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldRounded2ActionPerformed(evt);
            }
        });
        panelRounded2.add(jtextfieldRounded2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 260, 50));

        buttonRounded1.setBackground(new java.awt.Color(51, 204, 255));
        buttonRounded1.setForeground(new java.awt.Color(255, 255, 255));
        buttonRounded1.setText("MASUK");
        buttonRounded1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRounded1ActionPerformed(evt);
            }
        });
        panelRounded2.add(buttonRounded1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/download_edited.png"))); // NOI18N
        panelRounded2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 450, 480));

        panelRounded1.add(panelRounded2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        jPanel1.add(panelRounded1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfieldRounded1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldRounded1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldRounded1ActionPerformed

    private void jtextfieldRounded2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldRounded2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldRounded2ActionPerformed

    private void buttonRounded1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRounded1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRounded1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdmin().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jtextfield.ButtonRounded buttonRounded1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private jtextfield.JtextfieldRounded jtextfieldRounded1;
    private jtextfield.JtextfieldRounded jtextfieldRounded2;
    private jtextfield.PanelRounded panelRounded1;
    private jtextfield.PanelRounded panelRounded2;
    // End of variables declaration//GEN-END:variables
}
